// +build !ignore_autogenerated

/*
Copyright The NMState Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/



// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistentIP) DeepCopyInto(out *PersistentIP) {
*out = *in
out.TypeMeta = in.TypeMeta
in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
out.Spec = in.Spec
in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistentIP.
func (in *PersistentIP) DeepCopy() *PersistentIP {
	if in == nil { return nil }
	out := new(PersistentIP)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PersistentIP) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistentIPList) DeepCopyInto(out *PersistentIPList) {
*out = *in
out.TypeMeta = in.TypeMeta
in.ListMeta.DeepCopyInto(&out.ListMeta)
if in.Items != nil {
in, out := &in.Items, &out.Items
*out = make([]invalid type, len(*in))
for i := range *in {
}
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistentIPList.
func (in *PersistentIPList) DeepCopy() *PersistentIPList {
	if in == nil { return nil }
	out := new(PersistentIPList)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PersistentIPList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistentIPSpec) DeepCopyInto(out *PersistentIPSpec) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistentIPSpec.
func (in *PersistentIPSpec) DeepCopy() *PersistentIPSpec {
	if in == nil { return nil }
	out := new(PersistentIPSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistentIPStatus) DeepCopyInto(out *PersistentIPStatus) {
*out = *in
if in.IPs != nil {
in, out := &in.IPs, &out.IPs
*out = make([]string, len(*in))
copy(*out, *in)
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistentIPStatus.
func (in *PersistentIPStatus) DeepCopy() *PersistentIPStatus {
	if in == nil { return nil }
	out := new(PersistentIPStatus)
	in.DeepCopyInto(out)
	return out
}

